name: Construir Chanka Explore

on:
  workflow_dispatch:
  push:
    branches:
      - principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Preparar proyecto
        run: |
          unzip -o ChankaExplore-Android-Studio.zip
          ls -la ChankaExploreApp

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.13'

      - name: Generar AAB
        run: |
          gradle -p ChankaExploreApp bundleRelease

      - name: Guardar AAB
        uses: actions/upload-artifact@v4
        with:
          name: Chanka-Explore-AAB
          path: ChankaExploreApp/app/build/outputs/bundle/release/*.aab
